#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "my_idlers"
name = "My Idlers"
description.en = "View, organise and store information about your servers"
description.fr = "Visualiser, organiser et stocker des informations sur vos serveurs"

version = "3.0~ynh1"

maintainers = ["wbk"]

[upstream]
license = "MIT"
demo = "https://demo.myidlers.com/login"
userdoc = "https://lowendspirit.com/discussion/2449/my-idlers-self-hosted-web-app-for-your-servers-shared-hosting-and-domains-information/"
code = "https://github.com/cp6/my-idlers#install"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "100M"
ram.build = "150M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    # unable to get this to work, disable for now    
    #[install.path]
    #type = "path"
    #default = "/idlers"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"
    
[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/cp6/my-idlers/archive/refs/tags/3.0.tar.gz"
    sha256 = "48f147788736bc199194d56226cd48649970460b87b5ede6c26b3ead90bb8032"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-mbstring, php8.3-xml, php8.3-mysql, php8.3-intl, php8.3-pdo, php8.3-intl, php8.3-curl"

    [resources.database]
    type = "mysql"
