#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=.env --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# INSTALL APP WITH COMPOSER
#=================================================
ynh_script_progression "Installing app with Composer..."

ynh_composer_install
ynh_composer_exec install --no-dev

#=================================================
# BUILDING
#=================================================
ynh_script_progression "configuring $app..."

pushd "$install_dir"
	"php$php_version" artisan key:generate -n --force --env
	"php$php_version" artisan make:database $app
	"php$php_version" artisan migrate:fresh --seed -n --force
	"php$php_version" artisan config:clear -n
	"php$php_version" artisan config:cache -n
popd

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression "Finalizing installation..."

# Installation with curl: set up the first/single user
ynh_local_curl "/INSTALL_PATH" "key1=$admin" "key2=$email" "key3=$password" "key4=$password"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
